version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    command: >
      bash -c "
        docker-entrypoint.sh mysqld &
        sleep 30 && 
        mysql -u root -p123456 -e 'CREATE DATABASE IF NOT EXISTS store;' && 
        wait
      "
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p123456 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - demo

  ui:
    image: lani06/react:latest
    container_name: ui
    hostname: ui
    environment:
      #- API=192.168.1.12:57600
      - API_URL=http://localhost:8080      
    ports:
      - "3000:3000"
    networks:
      - demo


  api:
    image: lani06/storeapi:latest
    container_name: api
    hostname: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- mysql=192.168.1.10:3306
      - DB=Server=mysql;Database=store;Uid=root;Pwd=123456
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
#    entrypoint: ["./wait-for-it.sh", "mysql:3306", "--", "sh", "-c", "sleep 5 && your_api_start_command_here"]
    networks:
      - demo

networks:
  demo:
    driver: bridge
